// The MIT License
//
// Copyright (c) 2022 Temporal Technologies Inc.  All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/api/operatorservice/v1/service.proto

package operatorservice

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("temporal/api/operatorservice/v1/service.proto", fileDescriptor_a603f8bc80c66d47)
}

var fileDescriptor_a603f8bc80c66d47 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0xf7, 0xf5, 0xe0, 0x61, 0xa8, 0x14, 0x56, 0xf1, 0x47, 0x0e, 0x23, 0x06, 0xaf, 0x6e,
	0x88, 0x5a, 0x95, 0x4d, 0xd5, 0x6e, 0x22, 0x88, 0x3f, 0x68, 0x4b, 0xab, 0x3d, 0x78, 0x91, 0x6d,
	0xf2, 0xa8, 0x03, 0x49, 0x66, 0x9c, 0x99, 0x04, 0x2f, 0x82, 0x27, 0xcf, 0x22, 0x78, 0x12, 0x04,
	0x41, 0x50, 0xfc, 0x27, 0xbc, 0x7a, 0x8c, 0xb7, 0x1e, 0xcd, 0xe6, 0x22, 0x3d, 0xf5, 0x4f, 0x90,
	0x35, 0x3b, 0xab, 0x6e, 0xb7, 0xce, 0x76, 0xd3, 0x5b, 0x48, 0xde, 0xe7, 0xfb, 0x3e, 0x9b, 0x79,
	0xb3, 0x8f, 0x5c, 0xd4, 0xd8, 0x13, 0x5c, 0x86, 0xdd, 0x5a, 0x28, 0x58, 0x8d, 0x0b, 0x94, 0xa1,
	0xe6, 0x52, 0xa1, 0x1c, 0xb2, 0x36, 0xd6, 0x86, 0xf5, 0x5a, 0xf2, 0xd1, 0x13, 0x92, 0x6b, 0xee,
	0x9e, 0x33, 0xe5, 0x5e, 0x28, 0x98, 0x97, 0x29, 0xf7, 0x86, 0xf5, 0xca, 0x55, 0x5b, 0x9e, 0xc4,
	0x67, 0x03, 0x54, 0xfa, 0x89, 0x44, 0x25, 0x78, 0x5f, 0x25, 0xc1, 0x97, 0xbe, 0x1f, 0x27, 0x0b,
	0xab, 0x49, 0xf5, 0xc6, 0xb4, 0xda, 0x7d, 0x03, 0xe4, 0x44, 0xd0, 0xe9, 0x6c, 0x60, 0x28, 0xdb,
	0x4f, 0x03, 0xad, 0x25, 0xdb, 0x1a, 0x68, 0x54, 0x6e, 0xc3, 0xb3, 0x58, 0x78, 0x39, 0xd4, 0xfa,
	0xb4, 0x6f, 0x65, 0xa9, 0x1c, 0x3c, 0x95, 0xad, 0x3a, 0xee, 0x3b, 0x20, 0xa7, 0xd6, 0xb1, 0xc7,
	0x87, 0xb8, 0xcf, 0xeb, 0xa6, 0x35, 0x3a, 0x1f, 0x34, 0x6a, 0xb7, 0x4a, 0xf3, 0xa9, 0xdd, 0x5b,
	0x20, 0x27, 0x1f, 0x30, 0xa5, 0xf7, 0xb9, 0xd9, 0x1f, 0x3b, 0x0f, 0x33, 0x66, 0x37, 0x4a, 0xd2,
	0xa9, 0xd7, 0x2b, 0x20, 0x0b, 0xb7, 0xb1, 0x8b, 0x1a, 0x57, 0xc2, 0x1e, 0x2a, 0x11, 0xb6, 0xd1,
	0xbd, 0x66, 0x0d, 0xcd, 0x10, 0xc6, 0xe6, 0xfa, 0xe1, 0xc1, 0x54, 0xe4, 0x03, 0x90, 0x33, 0x41,
	0xa7, 0xb3, 0x2a, 0x1f, 0x89, 0x4e, 0xa8, 0x31, 0xfe, 0x43, 0x35, 0xb6, 0xba, 0x03, 0xa5, 0x51,
	0xba, 0xcb, 0x45, 0x66, 0x23, 0x17, 0x35, 0x6a, 0xc1, 0x0c, 0x09, 0xa9, 0x63, 0x3c, 0xf7, 0xd3,
	0x93, 0xfe, 0x57, 0xaf, 0x51, 0x70, 0x3e, 0x72, 0xcd, 0x96, 0xca, 0xc1, 0xa9, 0xd4, 0x0b, 0x32,
	0x1f, 0x9f, 0x71, 0xf2, 0x83, 0x72, 0xaf, 0x14, 0x1a, 0x09, 0x53, 0x6e, 0x2c, 0x16, 0x0f, 0x49,
	0xa5, 0xed, 0xdf, 0x03, 0x39, 0x7d, 0x07, 0xf5, 0x0a, 0x3e, 0x1f, 0xa8, 0xbb, 0xfd, 0x36, 0xef,
	0xb1, 0xfe, 0xb6, 0x79, 0x4f, 0xd8, 0xef, 0xcd, 0x01, 0xa4, 0xb1, 0x5a, 0x2e, 0x1f, 0x90, 0x0a,
	0x7e, 0x05, 0x52, 0x6d, 0x49, 0x0c, 0x35, 0x9a, 0xe3, 0xcd, 0x75, 0xbd, 0x67, 0x6d, 0x65, 0x0f,
	0x31, 0xda, 0xf7, 0x8f, 0x24, 0x2b, 0x7d, 0x82, 0x4f, 0x40, 0x2a, 0xc9, 0xc5, 0xc9, 0x33, 0x6f,
	0x16, 0xbd, 0x75, 0xff, 0x31, 0x6e, 0xcd, 0x94, 0x91, 0x9a, 0x7e, 0x04, 0x72, 0x36, 0x9e, 0x93,
	0xbc, 0x32, 0xe5, 0x06, 0x85, 0x66, 0x2c, 0x97, 0x35, 0x9e, 0xcd, 0x59, 0x22, 0x8c, 0x66, 0x73,
	0x17, 0x46, 0x63, 0xea, 0xec, 0x8c, 0xa9, 0xb3, 0x37, 0xa6, 0xf0, 0x32, 0xa2, 0xf0, 0x39, 0xa2,
	0xf0, 0x2d, 0xa2, 0x30, 0x8a, 0x28, 0xfc, 0x88, 0x28, 0xfc, 0x8c, 0xa8, 0xb3, 0x17, 0x51, 0x78,
	0x3d, 0xa1, 0xce, 0x68, 0x42, 0x9d, 0x9d, 0x09, 0x75, 0x48, 0x95, 0x71, 0x5b, 0xfb, 0xe6, 0x7c,
	0xd2, 0x6e, 0x2d, 0x5e, 0x9e, 0x6b, 0xf0, 0x78, 0x71, 0xfb, 0x2f, 0x86, 0xf1, 0x03, 0x96, 0x6f,
	0x23, 0xf3, 0xd5, 0x97, 0xb9, 0xf3, 0x0f, 0x13, 0x88, 0x71, 0x2f, 0x10, 0xcc, 0xcb, 0xac, 0x60,
	0x6f, 0xb3, 0xbe, 0x3b, 0x77, 0xe1, 0x4f, 0x8d, 0xef, 0x07, 0x82, 0xf9, 0x7e, 0xa6, 0xca, 0xf7,
	0x37, 0xeb, 0x5b, 0xc7, 0x7e, 0xef, 0xf1, 0xcb, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x26, 0x7b,
	0x7c, 0x3e, 0x51, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperatorServiceClient interface {
	// AddSearchAttributes add custom search attributes.
	//
	// Returns ALREADY_EXISTS status code if a Search Attribute with any of the specified names already exists
	// Returns INTERNAL status code with temporal.api.errordetails.v1.SystemWorkflowFailure in Error Details if registration process fails,
	AddSearchAttributes(ctx context.Context, in *AddSearchAttributesRequest, opts ...grpc.CallOption) (*AddSearchAttributesResponse, error)
	// RemoveSearchAttributes removes custom search attributes.
	//
	// Returns NOT_FOUND status code if a Search Attribute with any of the specified names is not registered
	RemoveSearchAttributes(ctx context.Context, in *RemoveSearchAttributesRequest, opts ...grpc.CallOption) (*RemoveSearchAttributesResponse, error)
	// ListSearchAttributes returns comprehensive information about search attributes.
	ListSearchAttributes(ctx context.Context, in *ListSearchAttributesRequest, opts ...grpc.CallOption) (*ListSearchAttributesResponse, error)
	// DeleteNamespace synchronously deletes a namespace and asynchronously reclaims all namespace resources.
	// (-- api-linter: core::0135::method-signature=disabled
	//     aip.dev/not-precedent: DeleteNamespace RPC doesn't follow Google API format. --)
	// (-- api-linter: core::0135::response-message-name=disabled
	//     aip.dev/not-precedent: DeleteNamespace RPC doesn't follow Google API format. --)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
	// AddOrUpdateRemoteCluster adds or updates remote cluster.
	AddOrUpdateRemoteCluster(ctx context.Context, in *AddOrUpdateRemoteClusterRequest, opts ...grpc.CallOption) (*AddOrUpdateRemoteClusterResponse, error)
	// RemoveRemoteCluster removes remote cluster.
	RemoveRemoteCluster(ctx context.Context, in *RemoveRemoteClusterRequest, opts ...grpc.CallOption) (*RemoveRemoteClusterResponse, error)
	// ListClusters returns information about Temporal clusters.
	ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error)
	// Get a registered incoming Nexus service. The returned version can be used for optimistic updates.
	GetNexusIncomingService(ctx context.Context, in *GetNexusIncomingServiceRequest, opts ...grpc.CallOption) (*GetNexusIncomingServiceResponse, error)
	// Optimistically create or update a Nexus service based on provided version.
	// To update an existing service, get the current service record via the `GetNexusIncomingService` API, modify it
	// and submit to this API.
	// Set version to 0 to create a new service.
	// If this request is accepted, the input is considered the "current" state of this service at the time it was
	// persisted and the updated version is returned.
	CreateOrUpdateNexusIncomingService(ctx context.Context, in *CreateOrUpdateNexusIncomingServiceRequest, opts ...grpc.CallOption) (*CreateOrUpdateNexusIncomingServiceResponse, error)
	// Delete an incoming Nexus service by its base URL.
	// (-- api-linter: core::0135::response-message-name=disabled
	//     aip.dev/not-precedent: DeleteNexusIncomingService RPC doesn't follow Google API format. --)
	DeleteNexusIncomingService(ctx context.Context, in *DeleteNexusIncomingServiceRequest, opts ...grpc.CallOption) (*DeleteNexusIncomingServiceResponse, error)
	// List all nexus incoming services. Use next_page_token in the response for pagination.
	ListNexusIncomingServices(ctx context.Context, in *ListNexusIncomingServicesRequest, opts ...grpc.CallOption) (*ListNexusIncomingServicesResponse, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) AddSearchAttributes(ctx context.Context, in *AddSearchAttributesRequest, opts ...grpc.CallOption) (*AddSearchAttributesResponse, error) {
	out := new(AddSearchAttributesResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/AddSearchAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RemoveSearchAttributes(ctx context.Context, in *RemoveSearchAttributesRequest, opts ...grpc.CallOption) (*RemoveSearchAttributesResponse, error) {
	out := new(RemoveSearchAttributesResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/RemoveSearchAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListSearchAttributes(ctx context.Context, in *ListSearchAttributesRequest, opts ...grpc.CallOption) (*ListSearchAttributesResponse, error) {
	out := new(ListSearchAttributesResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/DeleteNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) AddOrUpdateRemoteCluster(ctx context.Context, in *AddOrUpdateRemoteClusterRequest, opts ...grpc.CallOption) (*AddOrUpdateRemoteClusterResponse, error) {
	out := new(AddOrUpdateRemoteClusterResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/AddOrUpdateRemoteCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RemoveRemoteCluster(ctx context.Context, in *RemoveRemoteClusterRequest, opts ...grpc.CallOption) (*RemoveRemoteClusterResponse, error) {
	out := new(RemoveRemoteClusterResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/RemoveRemoteCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error) {
	out := new(ListClustersResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/ListClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) GetNexusIncomingService(ctx context.Context, in *GetNexusIncomingServiceRequest, opts ...grpc.CallOption) (*GetNexusIncomingServiceResponse, error) {
	out := new(GetNexusIncomingServiceResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/GetNexusIncomingService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) CreateOrUpdateNexusIncomingService(ctx context.Context, in *CreateOrUpdateNexusIncomingServiceRequest, opts ...grpc.CallOption) (*CreateOrUpdateNexusIncomingServiceResponse, error) {
	out := new(CreateOrUpdateNexusIncomingServiceResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/CreateOrUpdateNexusIncomingService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DeleteNexusIncomingService(ctx context.Context, in *DeleteNexusIncomingServiceRequest, opts ...grpc.CallOption) (*DeleteNexusIncomingServiceResponse, error) {
	out := new(DeleteNexusIncomingServiceResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/DeleteNexusIncomingService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListNexusIncomingServices(ctx context.Context, in *ListNexusIncomingServicesRequest, opts ...grpc.CallOption) (*ListNexusIncomingServicesResponse, error) {
	out := new(ListNexusIncomingServicesResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/ListNexusIncomingServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServiceServer is the server API for OperatorService service.
type OperatorServiceServer interface {
	// AddSearchAttributes add custom search attributes.
	//
	// Returns ALREADY_EXISTS status code if a Search Attribute with any of the specified names already exists
	// Returns INTERNAL status code with temporal.api.errordetails.v1.SystemWorkflowFailure in Error Details if registration process fails,
	AddSearchAttributes(context.Context, *AddSearchAttributesRequest) (*AddSearchAttributesResponse, error)
	// RemoveSearchAttributes removes custom search attributes.
	//
	// Returns NOT_FOUND status code if a Search Attribute with any of the specified names is not registered
	RemoveSearchAttributes(context.Context, *RemoveSearchAttributesRequest) (*RemoveSearchAttributesResponse, error)
	// ListSearchAttributes returns comprehensive information about search attributes.
	ListSearchAttributes(context.Context, *ListSearchAttributesRequest) (*ListSearchAttributesResponse, error)
	// DeleteNamespace synchronously deletes a namespace and asynchronously reclaims all namespace resources.
	// (-- api-linter: core::0135::method-signature=disabled
	//     aip.dev/not-precedent: DeleteNamespace RPC doesn't follow Google API format. --)
	// (-- api-linter: core::0135::response-message-name=disabled
	//     aip.dev/not-precedent: DeleteNamespace RPC doesn't follow Google API format. --)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
	// AddOrUpdateRemoteCluster adds or updates remote cluster.
	AddOrUpdateRemoteCluster(context.Context, *AddOrUpdateRemoteClusterRequest) (*AddOrUpdateRemoteClusterResponse, error)
	// RemoveRemoteCluster removes remote cluster.
	RemoveRemoteCluster(context.Context, *RemoveRemoteClusterRequest) (*RemoveRemoteClusterResponse, error)
	// ListClusters returns information about Temporal clusters.
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	// Get a registered incoming Nexus service. The returned version can be used for optimistic updates.
	GetNexusIncomingService(context.Context, *GetNexusIncomingServiceRequest) (*GetNexusIncomingServiceResponse, error)
	// Optimistically create or update a Nexus service based on provided version.
	// To update an existing service, get the current service record via the `GetNexusIncomingService` API, modify it
	// and submit to this API.
	// Set version to 0 to create a new service.
	// If this request is accepted, the input is considered the "current" state of this service at the time it was
	// persisted and the updated version is returned.
	CreateOrUpdateNexusIncomingService(context.Context, *CreateOrUpdateNexusIncomingServiceRequest) (*CreateOrUpdateNexusIncomingServiceResponse, error)
	// Delete an incoming Nexus service by its base URL.
	// (-- api-linter: core::0135::response-message-name=disabled
	//     aip.dev/not-precedent: DeleteNexusIncomingService RPC doesn't follow Google API format. --)
	DeleteNexusIncomingService(context.Context, *DeleteNexusIncomingServiceRequest) (*DeleteNexusIncomingServiceResponse, error)
	// List all nexus incoming services. Use next_page_token in the response for pagination.
	ListNexusIncomingServices(context.Context, *ListNexusIncomingServicesRequest) (*ListNexusIncomingServicesResponse, error)
}

// UnimplementedOperatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOperatorServiceServer struct {
}

func (*UnimplementedOperatorServiceServer) AddSearchAttributes(ctx context.Context, req *AddSearchAttributesRequest) (*AddSearchAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSearchAttributes not implemented")
}
func (*UnimplementedOperatorServiceServer) RemoveSearchAttributes(ctx context.Context, req *RemoveSearchAttributesRequest) (*RemoveSearchAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSearchAttributes not implemented")
}
func (*UnimplementedOperatorServiceServer) ListSearchAttributes(ctx context.Context, req *ListSearchAttributesRequest) (*ListSearchAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSearchAttributes not implemented")
}
func (*UnimplementedOperatorServiceServer) DeleteNamespace(ctx context.Context, req *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (*UnimplementedOperatorServiceServer) AddOrUpdateRemoteCluster(ctx context.Context, req *AddOrUpdateRemoteClusterRequest) (*AddOrUpdateRemoteClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrUpdateRemoteCluster not implemented")
}
func (*UnimplementedOperatorServiceServer) RemoveRemoteCluster(ctx context.Context, req *RemoveRemoteClusterRequest) (*RemoveRemoteClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRemoteCluster not implemented")
}
func (*UnimplementedOperatorServiceServer) ListClusters(ctx context.Context, req *ListClustersRequest) (*ListClustersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClusters not implemented")
}
func (*UnimplementedOperatorServiceServer) GetNexusIncomingService(ctx context.Context, req *GetNexusIncomingServiceRequest) (*GetNexusIncomingServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNexusIncomingService not implemented")
}
func (*UnimplementedOperatorServiceServer) CreateOrUpdateNexusIncomingService(ctx context.Context, req *CreateOrUpdateNexusIncomingServiceRequest) (*CreateOrUpdateNexusIncomingServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateNexusIncomingService not implemented")
}
func (*UnimplementedOperatorServiceServer) DeleteNexusIncomingService(ctx context.Context, req *DeleteNexusIncomingServiceRequest) (*DeleteNexusIncomingServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNexusIncomingService not implemented")
}
func (*UnimplementedOperatorServiceServer) ListNexusIncomingServices(ctx context.Context, req *ListNexusIncomingServicesRequest) (*ListNexusIncomingServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNexusIncomingServices not implemented")
}

func RegisterOperatorServiceServer(s *grpc.Server, srv OperatorServiceServer) {
	s.RegisterService(&_OperatorService_serviceDesc, srv)
}

func _OperatorService_AddSearchAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSearchAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).AddSearchAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/AddSearchAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).AddSearchAttributes(ctx, req.(*AddSearchAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RemoveSearchAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSearchAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RemoveSearchAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/RemoveSearchAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RemoveSearchAttributes(ctx, req.(*RemoveSearchAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListSearchAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSearchAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListSearchAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListSearchAttributes(ctx, req.(*ListSearchAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/DeleteNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_AddOrUpdateRemoteCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdateRemoteClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).AddOrUpdateRemoteCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/AddOrUpdateRemoteCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).AddOrUpdateRemoteCluster(ctx, req.(*AddOrUpdateRemoteClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RemoveRemoteCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRemoteClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RemoveRemoteCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/RemoveRemoteCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RemoveRemoteCluster(ctx, req.(*RemoveRemoteClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/ListClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListClusters(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_GetNexusIncomingService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNexusIncomingServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetNexusIncomingService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/GetNexusIncomingService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetNexusIncomingService(ctx, req.(*GetNexusIncomingServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_CreateOrUpdateNexusIncomingService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateNexusIncomingServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).CreateOrUpdateNexusIncomingService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/CreateOrUpdateNexusIncomingService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).CreateOrUpdateNexusIncomingService(ctx, req.(*CreateOrUpdateNexusIncomingServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DeleteNexusIncomingService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNexusIncomingServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DeleteNexusIncomingService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/DeleteNexusIncomingService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DeleteNexusIncomingService(ctx, req.(*DeleteNexusIncomingServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListNexusIncomingServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNexusIncomingServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListNexusIncomingServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/ListNexusIncomingServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListNexusIncomingServices(ctx, req.(*ListNexusIncomingServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OperatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.api.operatorservice.v1.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSearchAttributes",
			Handler:    _OperatorService_AddSearchAttributes_Handler,
		},
		{
			MethodName: "RemoveSearchAttributes",
			Handler:    _OperatorService_RemoveSearchAttributes_Handler,
		},
		{
			MethodName: "ListSearchAttributes",
			Handler:    _OperatorService_ListSearchAttributes_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _OperatorService_DeleteNamespace_Handler,
		},
		{
			MethodName: "AddOrUpdateRemoteCluster",
			Handler:    _OperatorService_AddOrUpdateRemoteCluster_Handler,
		},
		{
			MethodName: "RemoveRemoteCluster",
			Handler:    _OperatorService_RemoveRemoteCluster_Handler,
		},
		{
			MethodName: "ListClusters",
			Handler:    _OperatorService_ListClusters_Handler,
		},
		{
			MethodName: "GetNexusIncomingService",
			Handler:    _OperatorService_GetNexusIncomingService_Handler,
		},
		{
			MethodName: "CreateOrUpdateNexusIncomingService",
			Handler:    _OperatorService_CreateOrUpdateNexusIncomingService_Handler,
		},
		{
			MethodName: "DeleteNexusIncomingService",
			Handler:    _OperatorService_DeleteNexusIncomingService_Handler,
		},
		{
			MethodName: "ListNexusIncomingServices",
			Handler:    _OperatorService_ListNexusIncomingServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/api/operatorservice/v1/service.proto",
}
