// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package updatabletimer

import (
	"google.golang.org/protobuf/proto"
)

// Marshal an object of type UpdatableTimerExecutionOutcome to the protobuf v3 wire format
func (val *UpdatableTimerExecutionOutcome) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type UpdatableTimerExecutionOutcome from the protobuf v3 wire format
func (val *UpdatableTimerExecutionOutcome) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *UpdatableTimerExecutionOutcome) Size() int {
	return proto.Size(val)
}

// Equal returns whether two UpdatableTimerExecutionOutcome values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *UpdatableTimerExecutionOutcome) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *UpdatableTimerExecutionOutcome
	switch t := that.(type) {
	case *UpdatableTimerExecutionOutcome:
		that1 = t
	case UpdatableTimerExecutionOutcome:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type UpdatableTimerExecutionInfo to the protobuf v3 wire format
func (val *UpdatableTimerExecutionInfo) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type UpdatableTimerExecutionInfo from the protobuf v3 wire format
func (val *UpdatableTimerExecutionInfo) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *UpdatableTimerExecutionInfo) Size() int {
	return proto.Size(val)
}

// Equal returns whether two UpdatableTimerExecutionInfo values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *UpdatableTimerExecutionInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *UpdatableTimerExecutionInfo
	switch t := that.(type) {
	case *UpdatableTimerExecutionInfo:
		that1 = t
	case UpdatableTimerExecutionInfo:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type UpdatableTimerExecutionListInfo to the protobuf v3 wire format
func (val *UpdatableTimerExecutionListInfo) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type UpdatableTimerExecutionListInfo from the protobuf v3 wire format
func (val *UpdatableTimerExecutionListInfo) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *UpdatableTimerExecutionListInfo) Size() int {
	return proto.Size(val)
}

// Equal returns whether two UpdatableTimerExecutionListInfo values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *UpdatableTimerExecutionListInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *UpdatableTimerExecutionListInfo
	switch t := that.(type) {
	case *UpdatableTimerExecutionListInfo:
		that1 = t
	case UpdatableTimerExecutionListInfo:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}
