// The MIT License
//
// Copyright (c) 2022 Temporal Technologies Inc.  All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/api/enums/v1/event_type.proto

package enums

import (
	fmt "fmt"
	math "math"
	strconv "strconv"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Whenever this list of events is changed do change the function shouldBufferEvent in mutableStateBuilder.go to make sure to do the correct event ordering
type EventType int32

const (
	// Place holder and should never appear in a Workflow execution history
	EVENT_TYPE_UNSPECIFIED EventType = 0
	// Workflow execution has been triggered/started
	// It contains Workflow execution inputs, as well as Workflow timeout configurations
	EVENT_TYPE_WORKFLOW_EXECUTION_STARTED EventType = 1
	// Workflow execution has successfully completed and contains Workflow execution results
	EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED EventType = 2
	// Workflow execution has unsuccessfully completed and contains the Workflow execution error
	EVENT_TYPE_WORKFLOW_EXECUTION_FAILED EventType = 3
	// Workflow execution has timed out by the Temporal Server
	// Usually due to the Workflow having not been completed within timeout settings
	EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT EventType = 4
	// Workflow Task has been scheduled and the SDK client should now be able to process any new history events
	EVENT_TYPE_WORKFLOW_TASK_SCHEDULED EventType = 5
	// Workflow Task has started and the SDK client has picked up the Workflow Task and is processing new history events
	EVENT_TYPE_WORKFLOW_TASK_STARTED EventType = 6
	// Workflow Task has completed
	// The SDK client picked up the Workflow Task and processed new history events
	// SDK client may or may not ask the Temporal Server to do additional work, such as:
	// EVENT_TYPE_ACTIVITY_TASK_SCHEDULED
	// EVENT_TYPE_TIMER_STARTED
	// EVENT_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES
	// EVENT_TYPE_MARKER_RECORDED
	// EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED
	// EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED
	// EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED
	// EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED
	// EVENT_TYPE_WORKFLOW_EXECUTION_FAILED
	// EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED
	// EVENT_TYPE_WORKFLOW_EXECUTION_CONTINUED_AS_NEW
	EVENT_TYPE_WORKFLOW_TASK_COMPLETED EventType = 7
	// Workflow Task encountered a timeout
	// Either an SDK client with a local cache was not available at the time, or it took too long for the SDK client to process the task
	EVENT_TYPE_WORKFLOW_TASK_TIMED_OUT EventType = 8
	// Workflow Task encountered a failure
	// Usually this means that the Workflow was non-deterministic
	// However, the Workflow reset functionality also uses this event
	EVENT_TYPE_WORKFLOW_TASK_FAILED EventType = 9
	// Activity Task was scheduled
	// The SDK client should pick up this activity task and execute
	// This event type contains activity inputs, as well as activity timeout configurations
	EVENT_TYPE_ACTIVITY_TASK_SCHEDULED EventType = 10
	// Activity Task has started executing
	// The SDK client has picked up the Activity Task and is processing the Activity invocation
	EVENT_TYPE_ACTIVITY_TASK_STARTED EventType = 11
	// Activity Task has finished successfully
	// The SDK client has picked up and successfully completed the Activity Task
	// This event type contains Activity execution results
	EVENT_TYPE_ACTIVITY_TASK_COMPLETED EventType = 12
	// Activity Task has finished unsuccessfully
	// The SDK picked up the Activity Task but unsuccessfully completed it
	// This event type contains Activity execution errors
	EVENT_TYPE_ACTIVITY_TASK_FAILED EventType = 13
	// Activity has timed out according to the Temporal Server
	// Activity did not complete within the timeout settings
	EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT EventType = 14
	// A request to cancel the Activity has occurred
	// The SDK client will be able to confirm cancellation of an Activity during an Activity heartbeat
	EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED EventType = 15
	// Activity has been cancelled
	EVENT_TYPE_ACTIVITY_TASK_CANCELED EventType = 16
	// A timer has started
	EVENT_TYPE_TIMER_STARTED EventType = 17
	// A timer has fired
	EVENT_TYPE_TIMER_FIRED EventType = 18
	// A time has been cancelled
	EVENT_TYPE_TIMER_CANCELED EventType = 19
	// A request has been made to cancel the Workflow execution
	EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED EventType = 20
	// SDK client has confirmed the cancellation request and the Workflow execution has been cancelled
	EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED EventType = 21
	// Workflow has requested that the Temporal Server try to cancel another Workflow
	EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED EventType = 22
	// Temporal Server could not cancel the targeted Workflow
	// This is usually because the target Workflow could not be found
	EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED EventType = 23
	// Temporal Server has successfully requested the cancellation of the target Workflow
	EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_CANCEL_REQUESTED EventType = 24
	// A marker has been recorded.
	// This event type is transparent to the Temporal Server
	// The Server will only store it and will not try to understand it.
	EVENT_TYPE_MARKER_RECORDED EventType = 25
	// Workflow has received a Signal event
	// The event type contains the Signal name, as well as a Signal payload
	EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED EventType = 26
	// Workflow execution has been forcefully terminated
	// This is usually because the terminate Workflow API was called
	EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED EventType = 27
	// Workflow has successfully completed and a new Workflow has been started within the same transaction
	// Contains last Workflow execution results as well as new Workflow execution inputs
	EVENT_TYPE_WORKFLOW_EXECUTION_CONTINUED_AS_NEW EventType = 28
	// Temporal Server will try to start a child Workflow
	EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED EventType = 29
	// Child Workflow execution cannot be started/triggered
	// Usually due to a child Workflow ID collision
	EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_FAILED EventType = 30
	// Child Workflow execution has successfully started/triggered
	EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_STARTED EventType = 31
	// Child Workflow execution has successfully completed
	EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_COMPLETED EventType = 32
	// Child Workflow execution has unsuccessfully completed
	EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_FAILED EventType = 33
	// Child Workflow execution has been cancelled
	EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_CANCELED EventType = 34
	// Child Workflow execution has timed out by the Temporal Server
	EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TIMED_OUT EventType = 35
	// Child Workflow execution has been terminated
	EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TERMINATED EventType = 36
	// Temporal Server will try to Signal the targeted Workflow
	// Contains the Signal name, as well as a Signal payload
	EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED EventType = 37
	// Temporal Server cannot Signal the targeted Workflow
	// Usually because the Workflow could not be found
	EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED EventType = 38
	// Temporal Server has successfully Signaled the targeted Workflow
	EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_SIGNALED EventType = 39
	// Workflow search attributes should be updated and synchronized with the visibility store
	EVENT_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES EventType = 40
	// An update was accepted (i.e. validated)
	EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_ACCEPTED EventType = 41
	// An update was rejected (i.e. failed validation)
	EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_REJECTED EventType = 42
	// An update completed
	EVENT_TYPE_WORKFLOW_EXECUTION_UPDATE_COMPLETED EventType = 43
	// Some property or properties of the workflow as a whole have changed by non-workflow code.
	// The distinction of external vs. command-based modification is important so the SDK can
	// maintain determinism when using the command-based approach.
	EVENT_TYPE_WORKFLOW_PROPERTIES_MODIFIED_EXTERNALLY EventType = 44
	// Some property or properties of an already-scheduled activity have changed by non-workflow code.
	// The distinction of external vs. command-based modification is important so the SDK can
	// maintain determinism when using the command-based approach.
	EVENT_TYPE_ACTIVITY_PROPERTIES_MODIFIED_EXTERNALLY EventType = 45
	// Workflow properties modified by user workflow code
	EVENT_TYPE_WORKFLOW_PROPERTIES_MODIFIED     EventType = 46
	EVENT_TYPE_NEXUS_OPERATION_SCHEDULED        EventType = 47
	EVENT_TYPE_NEXUS_OPERATION_STARTED          EventType = 48
	EVENT_TYPE_NEXUS_OPERATION_COMPLETED        EventType = 49
	EVENT_TYPE_NEXUS_OPERATION_FAILED           EventType = 50
	EVENT_TYPE_NEXUS_OPERATION_TIMEDOUT         EventType = 51
	EVENT_TYPE_NEXUS_OPERATION_CANCEL_REQUESTED EventType = 52
)

var EventType_name = map[int32]string{
	0:  "Unspecified",
	1:  "WorkflowExecutionStarted",
	2:  "WorkflowExecutionCompleted",
	3:  "WorkflowExecutionFailed",
	4:  "WorkflowExecutionTimedOut",
	5:  "WorkflowTaskScheduled",
	6:  "WorkflowTaskStarted",
	7:  "WorkflowTaskCompleted",
	8:  "WorkflowTaskTimedOut",
	9:  "WorkflowTaskFailed",
	10: "ActivityTaskScheduled",
	11: "ActivityTaskStarted",
	12: "ActivityTaskCompleted",
	13: "ActivityTaskFailed",
	14: "ActivityTaskTimedOut",
	15: "ActivityTaskCancelRequested",
	16: "ActivityTaskCanceled",
	17: "TimerStarted",
	18: "TimerFired",
	19: "TimerCanceled",
	20: "WorkflowExecutionCancelRequested",
	21: "WorkflowExecutionCanceled",
	22: "RequestCancelExternalWorkflowExecutionInitiated",
	23: "RequestCancelExternalWorkflowExecutionFailed",
	24: "ExternalWorkflowExecutionCancelRequested",
	25: "MarkerRecorded",
	26: "WorkflowExecutionSignaled",
	27: "WorkflowExecutionTerminated",
	28: "WorkflowExecutionContinuedAsNew",
	29: "StartChildWorkflowExecutionInitiated",
	30: "StartChildWorkflowExecutionFailed",
	31: "ChildWorkflowExecutionStarted",
	32: "ChildWorkflowExecutionCompleted",
	33: "ChildWorkflowExecutionFailed",
	34: "ChildWorkflowExecutionCanceled",
	35: "ChildWorkflowExecutionTimedOut",
	36: "ChildWorkflowExecutionTerminated",
	37: "SignalExternalWorkflowExecutionInitiated",
	38: "SignalExternalWorkflowExecutionFailed",
	39: "ExternalWorkflowExecutionSignaled",
	40: "UpsertWorkflowSearchAttributes",
	41: "WorkflowExecutionUpdateAccepted",
	42: "WorkflowExecutionUpdateRejected",
	43: "WorkflowExecutionUpdateCompleted",
	44: "WorkflowPropertiesModifiedExternally",
	45: "ActivityPropertiesModifiedExternally",
	46: "WorkflowPropertiesModified",
	47: "NexusOperationScheduled",
	48: "NexusOperationStarted",
	49: "NexusOperationCompleted",
	50: "NexusOperationFailed",
	51: "NexusOperationTimedout",
	52: "NexusOperationCancelRequested",
}

var EventType_value = map[string]int32{
	"Unspecified":                                     0,
	"WorkflowExecutionStarted":                        1,
	"WorkflowExecutionCompleted":                      2,
	"WorkflowExecutionFailed":                         3,
	"WorkflowExecutionTimedOut":                       4,
	"WorkflowTaskScheduled":                           5,
	"WorkflowTaskStarted":                             6,
	"WorkflowTaskCompleted":                           7,
	"WorkflowTaskTimedOut":                            8,
	"WorkflowTaskFailed":                              9,
	"ActivityTaskScheduled":                           10,
	"ActivityTaskStarted":                             11,
	"ActivityTaskCompleted":                           12,
	"ActivityTaskFailed":                              13,
	"ActivityTaskTimedOut":                            14,
	"ActivityTaskCancelRequested":                     15,
	"ActivityTaskCanceled":                            16,
	"TimerStarted":                                    17,
	"TimerFired":                                      18,
	"TimerCanceled":                                   19,
	"WorkflowExecutionCancelRequested":                20,
	"WorkflowExecutionCanceled":                       21,
	"RequestCancelExternalWorkflowExecutionInitiated": 22,
	"RequestCancelExternalWorkflowExecutionFailed":    23,
	"ExternalWorkflowExecutionCancelRequested":        24,
	"MarkerRecorded":                                  25,
	"WorkflowExecutionSignaled":                       26,
	"WorkflowExecutionTerminated":                     27,
	"WorkflowExecutionContinuedAsNew":                 28,
	"StartChildWorkflowExecutionInitiated":            29,
	"StartChildWorkflowExecutionFailed":               30,
	"ChildWorkflowExecutionStarted":                   31,
	"ChildWorkflowExecutionCompleted":                 32,
	"ChildWorkflowExecutionFailed":                    33,
	"ChildWorkflowExecutionCanceled":                  34,
	"ChildWorkflowExecutionTimedOut":                  35,
	"ChildWorkflowExecutionTerminated":                36,
	"SignalExternalWorkflowExecutionInitiated":        37,
	"SignalExternalWorkflowExecutionFailed":           38,
	"ExternalWorkflowExecutionSignaled":               39,
	"UpsertWorkflowSearchAttributes":                  40,
	"WorkflowExecutionUpdateAccepted":                 41,
	"WorkflowExecutionUpdateRejected":                 42,
	"WorkflowExecutionUpdateCompleted":                43,
	"WorkflowPropertiesModifiedExternally":            44,
	"ActivityPropertiesModifiedExternally":            45,
	"WorkflowPropertiesModified":                      46,
	"NexusOperationScheduled":                         47,
	"NexusOperationStarted":                           48,
	"NexusOperationCompleted":                         49,
	"NexusOperationFailed":                            50,
	"NexusOperationTimedout":                          51,
	"NexusOperationCancelRequested":                   52,
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b482d2737d9259e4, []int{0}
}

func init() {
	proto.RegisterEnum("temporal.api.enums.v1.EventType", EventType_name, EventType_value)
}

func init() {
	proto.RegisterFile("temporal/api/enums/v1/event_type.proto", fileDescriptor_b482d2737d9259e4)
}

var fileDescriptor_b482d2737d9259e4 = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x51, 0x6f, 0xdb, 0x54,
	0x14, 0x8e, 0x0b, 0x0c, 0x76, 0x80, 0x61, 0xee, 0xd8, 0xd6, 0x85, 0xcd, 0x5b, 0xd7, 0x36, 0x6d,
	0xd3, 0xd6, 0x69, 0x9a, 0x8a, 0xa1, 0x0c, 0x09, 0x6e, 0xed, 0x13, 0x7a, 0x69, 0x62, 0x9b, 0xeb,
	0xeb, 0xb4, 0xe5, 0xc5, 0x2a, 0x52, 0x84, 0x22, 0xb1, 0xc5, 0x1a, 0xa1, 0xd2, 0xde, 0x78, 0xe7,
	0x85, 0x9f, 0x81, 0xf8, 0x09, 0xfc, 0x02, 0x1e, 0xfb, 0xb8, 0x47, 0x9a, 0xbe, 0x20, 0x9e, 0xf6,
	0x13, 0x90, 0x5d, 0x27, 0xf6, 0x6e, 0x12, 0xdb, 0xec, 0xcd, 0xd2, 0xfd, 0xbe, 0xef, 0x9c, 0xef,
	0xdc, 0x73, 0x7c, 0x0f, 0x54, 0x86, 0xbd, 0xa7, 0xc1, 0xe0, 0xf9, 0xe9, 0x8f, 0xb5, 0xd3, 0xa0,
	0x5f, 0xeb, 0x3d, 0xfb, 0xf9, 0xe9, 0x4f, 0xb5, 0xb3, 0x7a, 0xad, 0x77, 0xd6, 0x7b, 0x36, 0xf4,
	0x87, 0x2f, 0x82, 0x9e, 0x1e, 0x3c, 0x1f, 0x0c, 0x07, 0xe4, 0xd6, 0x18, 0xa7, 0x9f, 0x06, 0x7d,
	0x3d, 0xc2, 0xe9, 0x67, 0xf5, 0xea, 0xaf, 0x37, 0xe1, 0x3a, 0x86, 0x58, 0xf1, 0x22, 0xe8, 0x91,
	0x32, 0xdc, 0xc6, 0x2e, 0x5a, 0xc2, 0x17, 0x27, 0x0e, 0xfa, 0x9e, 0xe5, 0x3a, 0x68, 0xb0, 0x16,
	0x43, 0x53, 0x2d, 0x91, 0x0d, 0x58, 0x4d, 0x9d, 0x1d, 0xd9, 0xfc, 0xb0, 0xd5, 0xb6, 0x8f, 0x7c,
	0x3c, 0x46, 0xc3, 0x13, 0xcc, 0xb6, 0x7c, 0x57, 0x50, 0x2e, 0xd0, 0x54, 0x15, 0xb2, 0x09, 0x6b,
	0xd9, 0x50, 0xc3, 0xee, 0x38, 0x6d, 0x0c, 0xc1, 0x0b, 0x64, 0x1d, 0x56, 0xb2, 0xc1, 0x2d, 0xca,
	0xda, 0x68, 0xaa, 0x6f, 0xe5, 0xcb, 0x0a, 0xd6, 0x41, 0xd3, 0xb7, 0x3d, 0xa1, 0xbe, 0x4d, 0x2a,
	0xf0, 0x68, 0x16, 0x58, 0x50, 0xf7, 0xd0, 0x77, 0x8d, 0x03, 0x34, 0xbd, 0x50, 0xf4, 0x1d, 0xb2,
	0x02, 0x0f, 0xe7, 0xe3, 0x62, 0x47, 0xd7, 0x32, 0xd5, 0x12, 0x33, 0xef, 0x66, 0xe2, 0x92, 0xec,
	0xde, 0x23, 0xcb, 0xf0, 0x60, 0x2e, 0x2e, 0xf6, 0x7b, 0x5d, 0x12, 0xa3, 0x86, 0x60, 0x5d, 0x26,
	0x4e, 0x64, 0x0b, 0x20, 0x59, 0x90, 0x70, 0xb1, 0x85, 0xf7, 0x33, 0xd5, 0x12, 0x0b, 0x1f, 0x48,
	0xa9, 0xbd, 0x8e, 0x8b, 0x53, 0xfb, 0x30, 0x53, 0x2c, 0xf1, 0x79, 0x83, 0x6c, 0xc3, 0xc6, 0xfc,
	0xa0, 0xd4, 0x32, 0xb0, 0xed, 0x73, 0xfc, 0xd6, 0x43, 0x37, 0x8c, 0xfd, 0x11, 0x59, 0x85, 0xa5,
	0x1c, 0x38, 0x9a, 0xaa, 0x4a, 0xee, 0xc1, 0x62, 0x0a, 0x16, 0xc6, 0xe3, 0x13, 0xa3, 0x1f, 0x4b,
	0x4d, 0x7c, 0x75, 0xda, 0x62, 0x1c, 0x4d, 0x95, 0x90, 0xfb, 0x70, 0x77, 0xea, 0x6c, 0x22, 0x7c,
	0x93, 0xec, 0x82, 0x9e, 0xd3, 0xb8, 0x72, 0xce, 0x9f, 0x90, 0x2a, 0x54, 0x8a, 0x70, 0xd0, 0x54,
	0x6f, 0x11, 0x03, 0xbe, 0x4c, 0x61, 0x63, 0x95, 0xb1, 0x28, 0x1e, 0x0b, 0xe4, 0x16, 0x6d, 0xcf,
	0xd2, 0x60, 0x16, 0x13, 0x8c, 0x86, 0x01, 0x6f, 0x93, 0xaf, 0xe0, 0x8b, 0x37, 0x13, 0x89, 0x6f,
	0xef, 0x0e, 0x79, 0x02, 0x8f, 0x53, 0x0a, 0x59, 0x94, 0x29, 0xbf, 0x8b, 0x44, 0x83, 0x72, 0x8a,
	0xdc, 0xa1, 0xfc, 0x10, 0xb9, 0xcf, 0xd1, 0xb0, 0xb9, 0x89, 0xa6, 0x7a, 0x37, 0xbf, 0x1e, 0x2e,
	0xfb, 0xda, 0xa2, 0x61, 0x22, 0x65, 0xb2, 0x05, 0xeb, 0x39, 0x13, 0x8d, 0xbc, 0xc3, 0xac, 0xc8,
	0xf8, 0xa7, 0x05, 0x6e, 0xc7, 0xb6, 0x04, 0xb3, 0x3c, 0x34, 0x7d, 0xea, 0xfa, 0x16, 0x1e, 0xa9,
	0xf7, 0xc8, 0x63, 0x68, 0xa4, 0x38, 0x51, 0x93, 0xf8, 0xc6, 0x01, 0x6b, 0x9b, 0xd9, 0x55, 0xbe,
	0x4f, 0xf6, 0x60, 0xa7, 0x38, 0x31, 0xae, 0xac, 0x46, 0x6a, 0xb0, 0x99, 0x62, 0xcd, 0xc5, 0x8f,
	0x9b, 0xf5, 0x01, 0xa9, 0xc3, 0x76, 0x11, 0x42, 0x32, 0xa0, 0x0f, 0x89, 0x0e, 0xd5, 0x22, 0x94,
	0x38, 0xa7, 0x25, 0xb2, 0x03, 0x5b, 0x85, 0x42, 0x8c, 0xdb, 0xf4, 0x51, 0xd1, 0xa4, 0x92, 0x41,
	0x5f, 0x96, 0xee, 0x66, 0x3e, 0x25, 0xb9, 0xcf, 0x15, 0xa9, 0x0d, 0xaf, 0xda, 0xa2, 0xe0, 0x14,
	0xac, 0x92, 0xcf, 0x61, 0xef, 0xff, 0x91, 0xe3, 0x7a, 0x54, 0x48, 0x03, 0x6a, 0x05, 0xbb, 0x7f,
	0xd2, 0xa9, 0x6b, 0x52, 0x11, 0x3d, 0xc7, 0x45, 0x2e, 0x12, 0x8a, 0x8b, 0x94, 0x1b, 0x07, 0x3e,
	0x15, 0x82, 0xb3, 0x7d, 0x4f, 0xa0, 0xab, 0xae, 0x4b, 0x45, 0x9c, 0xa1, 0xee, 0x39, 0x26, 0x15,
	0xe1, 0x5f, 0xce, 0x40, 0x27, 0xf4, 0xb4, 0x51, 0x98, 0xc2, 0xf1, 0x1b, 0x34, 0x42, 0x4a, 0x35,
	0x7f, 0x26, 0x62, 0x4a, 0xd2, 0x40, 0x9b, 0xe4, 0x33, 0xd8, 0x9d, 0xc5, 0x71, 0xb8, 0xed, 0x20,
	0x17, 0x0c, 0x5d, 0xbf, 0x63, 0x9b, 0xd1, 0xb3, 0x3f, 0xa9, 0x4e, 0xfb, 0x44, 0xdd, 0x92, 0x78,
	0x93, 0xbf, 0x73, 0x0e, 0x6f, 0x7b, 0xde, 0xbb, 0x3d, 0x83, 0xa7, 0xea, 0xd2, 0x3a, 0x60, 0xe1,
	0xb1, 0xe7, 0xfa, 0x21, 0x8e, 0x5e, 0xdd, 0xc8, 0xe4, 0xd9, 0xab, 0x49, 0x6f, 0xd0, 0x14, 0x32,
	0x1e, 0xb1, 0x9d, 0x1c, 0xc5, 0xa4, 0x30, 0x75, 0xe9, 0xf9, 0x91, 0x91, 0x71, 0x03, 0xed, 0x92,
	0x35, 0x58, 0xce, 0x80, 0x45, 0x53, 0x11, 0x0e, 0x45, 0x43, 0xfa, 0x1b, 0x4c, 0x45, 0x96, 0xff,
	0xad, 0x7b, 0xfb, 0x7f, 0x2a, 0xe7, 0x17, 0x5a, 0xe9, 0xe5, 0x85, 0x56, 0x7a, 0x75, 0xa1, 0x29,
	0xbf, 0x8c, 0x34, 0xe5, 0xf7, 0x91, 0xa6, 0xfc, 0x35, 0xd2, 0x94, 0xf3, 0x91, 0xa6, 0xfc, 0x3d,
	0xd2, 0x94, 0x7f, 0x46, 0x5a, 0xe9, 0xd5, 0x48, 0x53, 0x7e, 0xbb, 0xd4, 0x4a, 0xe7, 0x97, 0x5a,
	0xe9, 0xe5, 0xa5, 0x56, 0x82, 0xc5, 0xfe, 0x40, 0x9f, 0xb9, 0xde, 0xed, 0xdf, 0x98, 0xec, 0x76,
	0x4e, 0xb8, 0x05, 0x3a, 0xca, 0x77, 0x4b, 0x3f, 0xa4, 0xb0, 0xfd, 0xc1, 0x6b, 0x5b, 0xe3, 0x93,
	0xe8, 0xe3, 0x8f, 0x85, 0x3b, 0x22, 0x06, 0xf4, 0x07, 0x3a, 0x0d, 0xfa, 0x3a, 0x46, 0x72, 0xdd,
	0xfa, 0xbf, 0x0b, 0xe5, 0xe4, 0xa4, 0xd9, 0xa4, 0x41, 0xbf, 0xd9, 0x8c, 0xce, 0x9a, 0xcd, 0x6e,
	0xfd, 0xfb, 0x6b, 0xd1, 0xa2, 0xd9, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xb7, 0x5e, 0xe8,
	0x92, 0x0a, 0x00, 0x00,
}

func (x EventType) String() string {
	s, ok := EventType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
