// The MIT License
//
// Copyright (c) 2022 Temporal Technologies Inc.  All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/api/enums/v1/task_queue.proto

package enums

import (
	fmt "fmt"
	math "math"
	strconv "strconv"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TaskQueueKind int32

const (
	TASK_QUEUE_KIND_UNSPECIFIED TaskQueueKind = 0
	// Tasks from a normal workflow task queue always include complete workflow history
	//
	// The task queue specified by the user is always a normal task queue. There can be as many
	// workers as desired for a single normal task queue. All those workers may pick up tasks from
	// that queue.
	TASK_QUEUE_KIND_NORMAL TaskQueueKind = 1
	// A sticky queue only includes new history since the last workflow task, and they are
	// per-worker.
	//
	// Sticky queues are created dynamically by each worker during their start up. They only exist
	// for the lifetime of the worker process. Tasks in a sticky task queue are only available to
	// the worker that created the sticky queue.
	//
	// Sticky queues are only for workflow tasks. There are no sticky task queues for activities.
	TASK_QUEUE_KIND_STICKY TaskQueueKind = 2
)

var TaskQueueKind_name = map[int32]string{
	0: "Unspecified",
	1: "Normal",
	2: "Sticky",
}

var TaskQueueKind_value = map[string]int32{
	"Unspecified": 0,
	"Normal":      1,
	"Sticky":      2,
}

func (TaskQueueKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf13a6eba37ec772, []int{0}
}

type TaskQueueType int32

const (
	TASK_QUEUE_TYPE_UNSPECIFIED TaskQueueType = 0
	// Workflow type of task queue.
	TASK_QUEUE_TYPE_WORKFLOW TaskQueueType = 1
	// Activity type of task queue.
	TASK_QUEUE_TYPE_ACTIVITY TaskQueueType = 2
	// Task queue type for dispatching Nexus requests.
	TASK_QUEUE_TYPE_NEXUS TaskQueueType = 3
)

var TaskQueueType_name = map[int32]string{
	0: "Unspecified",
	1: "Workflow",
	2: "Activity",
	3: "Nexus",
}

var TaskQueueType_value = map[string]int32{
	"Unspecified": 0,
	"Workflow":    1,
	"Activity":    2,
	"Nexus":       3,
}

func (TaskQueueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf13a6eba37ec772, []int{1}
}

// Specifies which category of tasks may reach a worker on a versioned task queue.
// Used both in a reachability query and its response.
type TaskReachability int32

const (
	TASK_REACHABILITY_UNSPECIFIED TaskReachability = 0
	// There's a possiblity for a worker to receive new workflow tasks. Workers should *not* be retired.
	TASK_REACHABILITY_NEW_WORKFLOWS TaskReachability = 1
	// There's a possiblity for a worker to receive existing workflow and activity tasks from existing workflows. Workers
	// should *not* be retired.
	// This enum value does not distinguish between open and closed workflows.
	TASK_REACHABILITY_EXISTING_WORKFLOWS TaskReachability = 2
	// There's a possiblity for a worker to receive existing workflow and activity tasks from open workflows. Workers
	// should *not* be retired.
	TASK_REACHABILITY_OPEN_WORKFLOWS TaskReachability = 3
	// There's a possiblity for a worker to receive existing workflow tasks from closed workflows. Workers may be
	// retired dependending on application requirements. For example, if there's no need to query closed workflows.
	TASK_REACHABILITY_CLOSED_WORKFLOWS TaskReachability = 4
)

var TaskReachability_name = map[int32]string{
	0: "Unspecified",
	1: "NewWorkflows",
	2: "ExistingWorkflows",
	3: "OpenWorkflows",
	4: "ClosedWorkflows",
}

var TaskReachability_value = map[string]int32{
	"Unspecified":       0,
	"NewWorkflows":      1,
	"ExistingWorkflows": 2,
	"OpenWorkflows":     3,
	"ClosedWorkflows":   4,
}

func (TaskReachability) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf13a6eba37ec772, []int{2}
}

func init() {
	proto.RegisterEnum("temporal.api.enums.v1.TaskQueueKind", TaskQueueKind_name, TaskQueueKind_value)
	proto.RegisterEnum("temporal.api.enums.v1.TaskQueueType", TaskQueueType_name, TaskQueueType_value)
	proto.RegisterEnum("temporal.api.enums.v1.TaskReachability", TaskReachability_name, TaskReachability_value)
}

func init() {
	proto.RegisterFile("temporal/api/enums/v1/task_queue.proto", fileDescriptor_cf13a6eba37ec772)
}

var fileDescriptor_cf13a6eba37ec772 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0xcf, 0x8e, 0x93, 0x40,
	0x1c, 0x07, 0x70, 0x86, 0x35, 0x1e, 0x26, 0xd1, 0x4c, 0x26, 0x59, 0x5d, 0x57, 0x9d, 0x75, 0x75,
	0xb3, 0x31, 0x3d, 0x40, 0x88, 0x37, 0x3c, 0x51, 0x3a, 0xab, 0x13, 0x10, 0x58, 0x18, 0xda, 0xc5,
	0x0b, 0x61, 0x95, 0xb8, 0x93, 0xfd, 0x03, 0x6e, 0x69, 0x93, 0xde, 0xbc, 0x79, 0xf5, 0x31, 0x8c,
	0x8f, 0xe0, 0x13, 0x78, 0x6c, 0x3c, 0xf5, 0x68, 0xe9, 0xc5, 0x78, 0xea, 0x23, 0x98, 0x12, 0xad,
	0x08, 0xbd, 0x91, 0x7c, 0x3f, 0xe1, 0xf7, 0x4d, 0xe6, 0x0b, 0x0f, 0x8b, 0xf4, 0x32, 0xcf, 0xae,
	0x93, 0x0b, 0x35, 0xc9, 0x85, 0x9a, 0x5e, 0x8d, 0x2e, 0x87, 0xea, 0x58, 0x53, 0x8b, 0x64, 0x78,
	0x1e, 0xbf, 0x1f, 0xa5, 0xa3, 0x54, 0xc9, 0xaf, 0xb3, 0x22, 0xc3, 0xdb, 0x7f, 0x9d, 0x92, 0xe4,
	0x42, 0xa9, 0x9c, 0x32, 0xd6, 0x3a, 0x67, 0xf0, 0x16, 0x4f, 0x86, 0xe7, 0xc7, 0x2b, 0x69, 0x89,
	0xab, 0xb7, 0x78, 0x0f, 0xde, 0xe7, 0x46, 0x60, 0xc5, 0xc7, 0x21, 0x0d, 0x69, 0x6c, 0x31, 0xa7,
	0x17, 0x87, 0x4e, 0xe0, 0x51, 0x93, 0x1d, 0x31, 0xda, 0x43, 0x12, 0xde, 0x85, 0x77, 0x9a, 0xc0,
	0x71, 0xfd, 0x57, 0x86, 0x8d, 0xc0, 0xa6, 0x2c, 0xe0, 0xcc, 0xb4, 0x22, 0x24, 0x77, 0x3e, 0x82,
	0xda, 0x29, 0x3e, 0xc9, 0xd3, 0xc6, 0x29, 0x1e, 0x79, 0xb4, 0x71, 0xea, 0x01, 0xdc, 0x69, 0x82,
	0x81, 0xeb, 0x5b, 0x47, 0xb6, 0x3b, 0x40, 0x60, 0x53, 0x6a, 0x98, 0x9c, 0xf5, 0x19, 0x8f, 0x90,
	0x8c, 0xef, 0xc1, 0xed, 0x66, 0xea, 0xd0, 0x93, 0x30, 0x40, 0x5b, 0x9d, 0xef, 0x00, 0xa2, 0x55,
	0x13, 0x3f, 0x4d, 0xde, 0x9c, 0x25, 0xa7, 0xe2, 0x42, 0x14, 0x13, 0xbc, 0x0f, 0x1f, 0x56, 0xde,
	0xa7, 0x86, 0xf9, 0xd2, 0xe8, 0x32, 0x9b, 0xf1, 0xa8, 0x51, 0xe7, 0x09, 0xdc, 0x6b, 0x13, 0x87,
	0x0e, 0xd6, 0xa5, 0x02, 0x04, 0xf0, 0x53, 0x78, 0xd0, 0x46, 0xf4, 0x84, 0x05, 0x9c, 0x39, 0x2f,
	0x6a, 0x52, 0xc6, 0x07, 0xf0, 0x51, 0x5b, 0xba, 0x1e, 0x75, 0x6a, 0x6a, 0x0b, 0x1f, 0xc2, 0xc7,
	0x6d, 0x65, 0xda, 0x6e, 0x40, 0x7b, 0x35, 0x77, 0xa3, 0xfb, 0x15, 0x4c, 0xe7, 0x44, 0x9a, 0xcd,
	0x89, 0xb4, 0x9c, 0x13, 0xf0, 0xa1, 0x24, 0xe0, 0x73, 0x49, 0xc0, 0xb7, 0x92, 0x80, 0x69, 0x49,
	0xc0, 0x8f, 0x92, 0x80, 0x9f, 0x25, 0x91, 0x96, 0x25, 0x01, 0x9f, 0x16, 0x44, 0x9a, 0x2e, 0x88,
	0x34, 0x5b, 0x10, 0x09, 0xee, 0x88, 0x4c, 0xd9, 0xb8, 0x8c, 0xee, 0xed, 0xf5, 0x63, 0x79, 0xab,
	0x01, 0x79, 0xe0, 0xf5, 0xfe, 0xbb, 0x9a, 0x15, 0xd9, 0x7f, 0x83, 0x7b, 0x5e, 0x7d, 0x7c, 0x91,
	0xef, 0xf2, 0x3f, 0x40, 0x64, 0x8a, 0x91, 0x0b, 0x85, 0x56, 0xbf, 0xeb, 0x6b, 0xbf, 0xe4, 0xdd,
	0x7f, 0x89, 0xae, 0x1b, 0xb9, 0xd0, 0xf5, 0x2a, 0xd3, 0xf5, 0xbe, 0x76, 0x7a, 0xb3, 0xda, 0xe8,
	0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0xd3, 0x4e, 0xba, 0xcd, 0x02, 0x00, 0x00,
}

func (x TaskQueueKind) String() string {
	s, ok := TaskQueueKind_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x TaskQueueType) String() string {
	s, ok := TaskQueueType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x TaskReachability) String() string {
	s, ok := TaskReachability_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
