// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/enums/v1/updatable_timer.proto

package enums

import (
	reflect "reflect"
	"strconv"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of an updatable timer execution.
// (-- api-linter: core::0216::synonyms=disabled
//
//	aip.dev/not-precedent: Named consistently with WorkflowExecutionStatus. --)
type UpdatableTimerExecutionStatus int32

const (
	UPDATABLE_TIMER_EXECUTION_STATUS_UNSPECIFIED UpdatableTimerExecutionStatus = 0
	// The timer is active and has not yet fired or been terminated.
	UPDATABLE_TIMER_EXECUTION_STATUS_RUNNING UpdatableTimerExecutionStatus = 1
	// The timer reached its deadline and fired.
	UPDATABLE_TIMER_EXECUTION_STATUS_FIRED UpdatableTimerExecutionStatus = 2
	// The timer was terminated before reaching its deadline.
	UPDATABLE_TIMER_EXECUTION_STATUS_TERMINATED UpdatableTimerExecutionStatus = 3
)

// Enum value maps for UpdatableTimerExecutionStatus.
var (
	UpdatableTimerExecutionStatus_name = map[int32]string{
		0: "UPDATABLE_TIMER_EXECUTION_STATUS_UNSPECIFIED",
		1: "UPDATABLE_TIMER_EXECUTION_STATUS_RUNNING",
		2: "UPDATABLE_TIMER_EXECUTION_STATUS_FIRED",
		3: "UPDATABLE_TIMER_EXECUTION_STATUS_TERMINATED",
	}
	UpdatableTimerExecutionStatus_value = map[string]int32{
		"UPDATABLE_TIMER_EXECUTION_STATUS_UNSPECIFIED": 0,
		"UPDATABLE_TIMER_EXECUTION_STATUS_RUNNING":     1,
		"UPDATABLE_TIMER_EXECUTION_STATUS_FIRED":       2,
		"UPDATABLE_TIMER_EXECUTION_STATUS_TERMINATED":  3,
	}
)

func (x UpdatableTimerExecutionStatus) Enum() *UpdatableTimerExecutionStatus {
	p := new(UpdatableTimerExecutionStatus)
	*p = x
	return p
}

func (x UpdatableTimerExecutionStatus) String() string {
	switch x {
	case UPDATABLE_TIMER_EXECUTION_STATUS_UNSPECIFIED:
		return "Unspecified"
	case UPDATABLE_TIMER_EXECUTION_STATUS_RUNNING:
		return "Running"
	case UPDATABLE_TIMER_EXECUTION_STATUS_FIRED:
		return "Fired"
	case UPDATABLE_TIMER_EXECUTION_STATUS_TERMINATED:
		return "Terminated"
	default:
		return strconv.Itoa(int(x))
	}

}

func (UpdatableTimerExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_api_enums_v1_updatable_timer_proto_enumTypes[0].Descriptor()
}

func (UpdatableTimerExecutionStatus) Type() protoreflect.EnumType {
	return &file_temporal_api_enums_v1_updatable_timer_proto_enumTypes[0]
}

func (x UpdatableTimerExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatableTimerExecutionStatus.Descriptor instead.
func (UpdatableTimerExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_temporal_api_enums_v1_updatable_timer_proto_rawDescGZIP(), []int{0}
}

var File_temporal_api_enums_v1_updatable_timer_proto protoreflect.FileDescriptor

const file_temporal_api_enums_v1_updatable_timer_proto_rawDesc = "" +
	"\n" +
	"+temporal/api/enums/v1/updatable_timer.proto\x12\x15temporal.api.enums.v1*\xdc\x01\n" +
	"\x1dUpdatableTimerExecutionStatus\x120\n" +
	",UPDATABLE_TIMER_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12,\n" +
	"(UPDATABLE_TIMER_EXECUTION_STATUS_RUNNING\x10\x01\x12*\n" +
	"&UPDATABLE_TIMER_EXECUTION_STATUS_FIRED\x10\x02\x12/\n" +
	"+UPDATABLE_TIMER_EXECUTION_STATUS_TERMINATED\x10\x03B\x8b\x01\n" +
	"\x18io.temporal.api.enums.v1B\x13UpdatableTimerProtoP\x01Z!go.temporal.io/api/enums/v1;enums\xaa\x02\x17Temporalio.Api.Enums.V1\xea\x02\x1aTemporalio::Api::Enums::V1b\x06proto3"

var (
	file_temporal_api_enums_v1_updatable_timer_proto_rawDescOnce sync.Once
	file_temporal_api_enums_v1_updatable_timer_proto_rawDescData []byte
)

func file_temporal_api_enums_v1_updatable_timer_proto_rawDescGZIP() []byte {
	file_temporal_api_enums_v1_updatable_timer_proto_rawDescOnce.Do(func() {
		file_temporal_api_enums_v1_updatable_timer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_enums_v1_updatable_timer_proto_rawDesc), len(file_temporal_api_enums_v1_updatable_timer_proto_rawDesc)))
	})
	return file_temporal_api_enums_v1_updatable_timer_proto_rawDescData
}

var file_temporal_api_enums_v1_updatable_timer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_api_enums_v1_updatable_timer_proto_goTypes = []any{
	(UpdatableTimerExecutionStatus)(0), // 0: temporal.api.enums.v1.UpdatableTimerExecutionStatus
}
var file_temporal_api_enums_v1_updatable_timer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temporal_api_enums_v1_updatable_timer_proto_init() }
func file_temporal_api_enums_v1_updatable_timer_proto_init() {
	if File_temporal_api_enums_v1_updatable_timer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_enums_v1_updatable_timer_proto_rawDesc), len(file_temporal_api_enums_v1_updatable_timer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_enums_v1_updatable_timer_proto_goTypes,
		DependencyIndexes: file_temporal_api_enums_v1_updatable_timer_proto_depIdxs,
		EnumInfos:         file_temporal_api_enums_v1_updatable_timer_proto_enumTypes,
	}.Build()
	File_temporal_api_enums_v1_updatable_timer_proto = out.File
	file_temporal_api_enums_v1_updatable_timer_proto_goTypes = nil
	file_temporal_api_enums_v1_updatable_timer_proto_depIdxs = nil
}
