// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package enums

import (
	"fmt"
)

var (
	UpdatableTimerExecutionStatus_shorthandValue = map[string]int32{
		"Unspecified": 0,
		"Running":     1,
		"Fired":       2,
		"Terminated":  3,
	}
)

// UpdatableTimerExecutionStatusFromString parses a UpdatableTimerExecutionStatus value from  either the protojson
// canonical SCREAMING_CASE enum or the traditional temporal PascalCase enum to UpdatableTimerExecutionStatus
func UpdatableTimerExecutionStatusFromString(s string) (UpdatableTimerExecutionStatus, error) {
	if v, ok := UpdatableTimerExecutionStatus_value[s]; ok {
		return UpdatableTimerExecutionStatus(v), nil
	} else if v, ok := UpdatableTimerExecutionStatus_shorthandValue[s]; ok {
		return UpdatableTimerExecutionStatus(v), nil
	}
	return UpdatableTimerExecutionStatus(0), fmt.Errorf("%s is not a valid UpdatableTimerExecutionStatus", s)
}
